name: "Build and Deploy Telegram Bot"
on:
  push:
    branches: ["master"]
    paths: ["backend/src/Microservices/TelegramBot/**"]
  workflow_dispatch:
jobs:
  build:
    name: "Build Telegram Bot"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2

      - name: "Login to GitHub Registry"
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: "Publish Telegram Bot Image"
        uses: docker/build-push-action@v4
        with:
          context: ./backend/src
          file: ./backend/src/Microservices/TelegramBot/Filer.TelegramBot.Presentation/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REGISTRY_USERNAME }}/filer-telegram-bot:latest
          platforms: linux/amd64
          provenance: false

  deploy:
    name: "Deploy Telegram Bot"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Prepare Kubernetes secrets.yaml
        run: |
          FILE_CONTENT=$(cat backend/infra/kubernetes/TelegramBot/secrets.yaml)

          for SECRET_NAME in ${{ toJson(secrets) }}; do
            SECRET_VALUE=${{ secrets[SECRET_NAME] }}
            FILE_CONTENT=${FILE_CONTENT//$\{$SECRET_NAME\}/$SECRET_VALUE}
          done

          echo "$FILE_CONTENT" > secrets.yaml

      - name: "Copy Kubernetes files to server"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          proxy_host: ${{ secrets.PROXY_SSH_HOST }}
          proxy_username: ${{ secrets.PROXY_SSH_USERNAME }}
          proxy_password: ${{ secrets.PROXY_SSH_PASSWORD }}
          proxy_port: ${{ secrets.PROXY_SSH_PORT }}
          source: "backend/infra/kubernetes/TelegramBot/"
          target: /home/${{ secrets.SSH_USERNAME }}/github/kubernetes/TelegramBot
          strip_components: 4

      - name: "Apply Kubernetes files"
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          proxy_host: ${{ secrets.PROXY_SSH_HOST }}
          proxy_username: ${{ secrets.PROXY_SSH_USERNAME }}
          proxy_password: ${{ secrets.PROXY_SSH_PASSWORD }}
          proxy_port: ${{ secrets.PROXY_SSH_PORT }}
          script: |
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S microk8s kubectl apply -f /home/${{ secrets.SSH_USERNAME }}/github/kubernetes/TelegramBot/secret.yaml

            echo ${{ secrets.SSH_PASSWORD }} | sudo -S microk8s kubectl apply -f /home/${{ secrets.SSH_USERNAME }}/github/kubernetes/TelegramBot/deployment.yaml

            echo ${{ secrets.SSH_PASSWORD }} | sudo -S microk8s kubectl apply -f /home/${{ secrets.SSH_USERNAME }}/github/kubernetes/TelegramBot/service.yaml
