name: "Deploy Telegram Bot"
on:
  push:
    branches: ["master"]
    paths: ["infra/kubernetes/TelegramBot/**"]
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy Telegram Bot"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Prepare Kubernetes secrets.yaml
        run: |
          FILE_CONTENT=$(cat backend/infra/kubernetes/TelegramBot/secrets.yaml)

          for SECRET_NAME in ${{ toJson(secrets) }}; do
            SECRET_VALUE=${{ secrets[SECRET_NAME] }}
            FILE_CONTENT=${FILE_CONTENT//$\{$SECRET_NAME\}/$SECRET_VALUE}
          done

          echo "$FILE_CONTENT" > secrets.yaml

      - name: "Copy Kubernetes files to server"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          proxy_host: ${{ secrets.PROXY_SSH_HOST }}
          proxy_username: ${{ secrets.PROXY_SSH_USERNAME }}
          proxy_password: ${{ secrets.PROXY_SSH_PASSWORD }}
          proxy_port: ${{ secrets.PROXY_SSH_PORT }}
          source: "backend/infra/kubernetes/TelegramBot/"
          target: /home/${{ secrets.SSH_USERNAME }}/github/kubernetes/TelegramBot
          strip_components: 4

      - name: "Apply Kubernetes files"
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          proxy_host: ${{ secrets.PROXY_SSH_HOST }}
          proxy_username: ${{ secrets.PROXY_SSH_USERNAME }}
          proxy_password: ${{ secrets.PROXY_SSH_PASSWORD }}
          proxy_port: ${{ secrets.PROXY_SSH_PORT }}
          script: |
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S microk8s kubectl apply -f /home/${{ secrets.SSH_USERNAME }}/github/kubernetes/TelegramBot/secret.yaml

            echo ${{ secrets.SSH_PASSWORD }} | sudo -S microk8s kubectl apply -f /home/${{ secrets.SSH_USERNAME }}/github/kubernetes/TelegramBot/deployment.yaml

            echo ${{ secrets.SSH_PASSWORD }} | sudo -S microk8s kubectl apply -f /home/${{ secrets.SSH_USERNAME }}/github/kubernetes/TelegramBot/service.yaml
